---
shared:
  image: node:8
jobs:
  validate_templates:
    requires: [~pr, ~commit]
    steps:
    - install_prerequisites: npm install -g screwdriver-template-main
    - validate_default_template: template-validate
    - validate_nodejs_template: |
        export SD_TEMPLATE_PATH=./templates/nodejs.yaml
        template-validate

  publish_default_template:
    requires: [validate_templates]
    # Don't need to set SD_TEMPLATE_PATH since it is at the default (sd-template.yaml)
    # environment:
    #   SD_TEMPLATE_PATH: ./sd-template.yaml
    steps:
    - install_prerequisites: npm install -g screwdriver-template-main
    - publish:  template-publish
    - autotag: template-tag --name nodejs/test --tag latest

  publish_nodejs_template:
    requires: [validate_templates]
    environment:
      SD_TEMPLATE_PATH: ./templates/nodejs.yaml
    steps:
    - install_prerequisites: npm install -g screwdriver-template-main
    - publish:  template-publish
    - autotag: template-tag --name golang/init --tag stable
